In [262]:
import cv2

import os

from glob import glob

anomalous_data_dir = os.path.join('.','assets',  'data', 'anomalous_dice', '*.jpg')
normal_data_dir = os.path.join('.','assets',  'data', 'normal_dice', '*')

anomalous_files = glob(anomalous_data_dir)
print(f"{len(anomalous_files)} anomalous files found")

normal_files_folders = glob(normal_data_dir)
normal_files_paths = []
labels = []
for folder in normal_files_folders:
    files = glob(folder + '\\*.jpg')
    normal_files_paths += files
    labels += [int(os.path.basename(folder))] * len(files)

print(f"{len(normal_files_paths)} normal files found")
print(f"{len(labels)} normal files labels found")
# for x in range(len(anomalous_files)):
#    print(anomalous_files[x])

img_size = 224
normal_images = []
threshold_im = []

82 anomalous files found
1077 normal files found
1077 normal files labels found

In [263]:
for img in normal_files_paths:
    try:
        img_arr = cv2.imread(img, cv2.IMREAD_GRAYSCALE)
        img_arr.shape
        resized_arr = cv2.resize(img_arr, (img_size, img_size))  # Reshaping images to preferred size
        _, thresh = cv2.threshold(resized_arr, 80, 255, cv2.THRESH_BINARY_INV)
        normal_images.append(resized_arr)
        threshold_im.append(thresh)
    except Exception as e:
        print(e)

In [264]:
import pandas as pd

df = pd.DataFrame(list(zip(labels, normal_images,threshold_im)),
               columns =['class', 'gray_arr', 'thresh'])

In [265]:
import numpy as np

df['mean_thresh'] = df['thresh'].apply(lambda x: np.mean(x))

In [266]:
df = df.groupby('class')['mean_thresh'].describe()

In [267]:
df.to_pickle('data/values_thresh_mask.pkl')

In [268]:
df[['mean','max']].iloc[0][0]

24.89701493461462

In [269]:
df

,count,mean,std,min,25%,50%,75%,max
class,,,,,,,,
0,103.0,24.897015,0.338795,24.231505,24.658402,24.861687,25.125957,25.791713
1,91.0,29.289267,0.551042,28.129484,28.861308,29.252631,29.689692,30.462173
2,63.0,58.946840,1.013315,56.070930,58.380750,59.008390,59.704640,60.599091
3,64.0,29.067293,0.461456,28.220962,28.696140,29.092544,29.369519,30.817921
4,120.0,37.662127,0.623821,35.732322,37.331917,37.645737,37.930335,39.432099
5,101.0,37.641435,0.596707,36.265944,37.231545,37.582211,38.044683,39.533741
6,178.0,46.033047,0.932312,43.365653,45.603052,46.043925,46.455576,54.012675
7,140.0,53.212896,0.900445,50.821110,52.578250,53.209702,53.866565,55.760922
8,72.0,58.905901,1.343751,54.673350,58.291813,59.178641,59.688123,61.168288
9,62.0,58.489195,1.413682,54.500558,57.792495,58.800024,59.576316,60.792211
10,83.0,58.405028,1.178226,54.851224,57.882703,58.678053,59.239627,60.751555