In [70]:
import cv2

import os

from glob import glob

anomalous_data_dir = os.path.join('.','assets',  'data', 'anomalous_dice', '*.jpg')
normal_data_dir = os.path.join('.','assets',  'data', 'normal_dice', '*')

anomalous_files = glob(anomalous_data_dir)
print(f"{len(anomalous_files)} anomalous files found")

normal_files_folders = glob(normal_data_dir)
normal_files_paths = []
labels = []
for folder in normal_files_folders:
    files = glob(folder + '\\*.jpg')
    normal_files_paths += files
    labels += [int(os.path.basename(folder))] * len(files)

print(f"{len(normal_files_paths)} normal files found")
print(f"{len(labels)} normal files labels found")
# for x in range(len(anomalous_files)):
#    print(anomalous_files[x])

img_size = 224
normal_images = []
threshold_im = []

82 anomalous files found
1077 normal files found
1077 normal files labels found

In [71]:
for img in normal_files_paths:
    try:
        img_arr = cv2.imread(img, cv2.IMREAD_GRAYSCALE)
        img_arr.shape
        resized_arr = cv2.resize(img_arr, (img_size, img_size))  # Reshaping images to preferred size
        _, thresh = cv2.threshold(resized_arr, 150, 255, cv2.THRESH_BINARY_INV)
        normal_images.append(resized_arr)
        threshold_im.append(thresh)
    except Exception as e:
        print(e)

In [72]:
import pandas as pd

df = pd.DataFrame(list(zip(labels, normal_images,threshold_im)),
               columns =['class', 'gray_arr', 'thresh'])

In [73]:
import numpy as np

df['mean_thresh'] = df['thresh'].apply(lambda x: np.mean(x))

In [74]:
df = df.groupby('class')['mean_thresh'].describe()

In [75]:
df.to_pickle('values_thresh_mask.pkl')

In [76]:
df[['min','max']].iloc[0][1]

37.04350685586735

In [77]:
df

,count,mean,std,min,25%,50%,75%,max
class,,,,,,,,
0,103.0,33.651815,1.041681,32.098613,32.881258,33.394551,34.161950,37.043507
1,91.0,38.715801,1.474621,36.194794,37.648278,38.400430,39.823422,42.237424
2,63.0,71.598796,1.253168,69.574099,70.575275,71.439234,72.387048,75.037368
3,64.0,38.154266,1.002309,36.377750,37.640655,38.151407,38.732038,42.638911
4,120.0,47.599475,1.301026,44.392239,46.675378,47.601592,48.567193,51.319157
5,101.0,47.669647,1.568956,44.361747,46.653779,47.411013,48.666295,52.056063
6,178.0,56.738771,1.605969,52.869200,55.486488,56.703653,57.590482,65.742188
7,140.0,64.484692,1.609161,60.827786,63.203673,64.471660,65.653251,68.328982
8,72.0,71.666235,1.046983,69.696070,70.835733,71.538335,72.298111,74.849330
9,62.0,71.450546,1.063714,70.031489,70.671835,71.279147,71.970314,74.478336
10,83.0,71.279117,1.027804,69.375897,70.618473,71.190210,71.647600,74.752770